// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALt3iGlCQyT_NJwRvWt7CK5vEObyzzZy8',
    appId: '1:1019132970318:web:dede2718b68f057db6ca1f',
    messagingSenderId: '1019132970318',
    projectId: 'receipt-tracker-b4ccd',
    authDomain: 'receipt-tracker-b4ccd.firebaseapp.com',
    storageBucket: 'receipt-tracker-b4ccd.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBluw3oBzUcstGttjP8wodUStkWoeOH0Ho',
    appId: '1:1019132970318:android:0894ce79443110bcb6ca1f',
    messagingSenderId: '1019132970318',
    projectId: 'receipt-tracker-b4ccd',
    storageBucket: 'receipt-tracker-b4ccd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDedmd-I9WSLAc5ffT31Reix4bR7HQNs3M',
    appId: '1:1019132970318:ios:76b527f9410371adb6ca1f',
    messagingSenderId: '1019132970318',
    projectId: 'receipt-tracker-b4ccd',
    storageBucket: 'receipt-tracker-b4ccd.firebasestorage.app',
    iosClientId: '1019132970318-6vhvdfn4q3oir7iu3eroeh9t0087c61h.apps.googleusercontent.com',
    iosBundleId: 'com.example.invoiceTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDedmd-I9WSLAc5ffT31Reix4bR7HQNs3M',
    appId: '1:1019132970318:ios:76b527f9410371adb6ca1f',
    messagingSenderId: '1019132970318',
    projectId: 'receipt-tracker-b4ccd',
    storageBucket: 'receipt-tracker-b4ccd.firebasestorage.app',
    iosClientId: '1019132970318-6vhvdfn4q3oir7iu3eroeh9t0087c61h.apps.googleusercontent.com',
    iosBundleId: 'com.example.invoiceTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyALt3iGlCQyT_NJwRvWt7CK5vEObyzzZy8',
    appId: '1:1019132970318:web:4df220b08656e3fbb6ca1f',
    messagingSenderId: '1019132970318',
    projectId: 'receipt-tracker-b4ccd',
    authDomain: 'receipt-tracker-b4ccd.firebaseapp.com',
    storageBucket: 'receipt-tracker-b4ccd.firebasestorage.app',
  );

}